[package]
name = "new_R_Shell"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
colored = "3.1.1"
crossterm = "0.29.0"
dirs = "6.0.0"
glob = "0.3.3"
nix = { version = "0.31.1", features = ["process", "signal", "fs", "term"] }
nu-ansi-term = "0.50.3"
reedline = "0.45.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
toml = "1.0.3"
